OutdoorPower/Models/Feedback.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace OutdoorPower.Models
{
    public class Feedback
    {
        public int Id { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "Your name is required.")]
        public string Name { get; set; }
        [Required]
        [StringLength(100, ErrorMessage = "Email address is required.")]
        [RegularExpression(@"[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
        [Required]
        [StringLength(1000, ErrorMessage = "A message is required.")]
        [MaxLength(1000)]
        public string Message { get; set; }
        public bool ContactMe { get; set; }
    }
}

OutdoorPower/Controllers/FeedbackController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using OutdoorPower.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace OutdoorPower.Controllers
{
    public class FeedbackController : Controller
    {
        private readonly IFeedbackRepository _feedbackRepository;
        
        FeedbackController(FeedbackRepository feedbackRepository)
        {
            _feedbackRepository = feedbackRepository;
        }
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(Feedback feedback)
        {
            if (ModelState.IsValid)
            {
                _feedbackRepository.AddFeedback(feedback);
                return RedirectToAction("FeedbackComplete");
            }
            return View(feedback);
        }

        public IActionResult FeedbackComplete()
        {
            return View();
        }
    }
}

OutdoorPower/Views/Feedback/FeedbackComplete.cshtml

@{
    ViewData["Title"] = "FeedbackComplete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>FeedbackComplete</h1>


OutdoorPower/Views/Feedback/Index.cshtml
@model Feedback
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

    <form asp-controller="Feedback" asp-action="Index" method="post" class="form-horizontal" role="form">
        <div class="form-group row">
            <label asp-for="Name" class="col-md-2 col-form-label" control-label></label>
            <div class="col-md-5">
                <select asp-for="Name" class="form-control" />
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="Email" class="col-md-2 col-form-label" control-label></label>
            <div class="col-md-5">
                <select asp-for="Email" class="form-control" />
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="ContactMe" class="col-md-2 col-form-label" control-label></label>
            <div class="col-md-5">
                <select asp-for="ContactMe" class="form-control" />
            </div>
        </div>
        <div class="form-group row">
            <div class="col-md-offset-2 col-md-5">
                <input type="submit" class="btn-btn-primary" value="Send" />
            </div>
        </div>
    </form>
